# Generated by Django 5.2.6 on 2025-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piatto',
            options={'verbose_name_plural': 'Piatti'},
        ),
        migrations.AddField(
            model_name='piatto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='piatti/'),
        ),
        migrations.AddField(
            model_name='piatto',
            name='ingredienti',
            field=models.CharField(choices=[('carne', 'Carne'), ('pesce', 'Pesce'), ('vegano', 'Vegano'), ('vegetariano', 'Vegetariano')], default='carne', max_length=20),
        ),
        migrations.AddField(
            model_name='piatto',
            name='portata',
            field=models.CharField(choices=[('antipasto', 'Antipasto'), ('primo', 'Primo'), ('secondo', 'Secondo'), ('dessert', 'Dessert')], default='primo', max_length=20),
        ),
    ]
