# Generated by Django 5.2.6 on 2025-09-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0002_alter_piatto_options_piatto_foto_piatto_ingredienti_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orario_ritiro', models.DateTimeField()),
                ('stato', models.CharField(choices=[('pending', 'In attesa'), ('completed', 'Completato'), ('cancelled', 'Cancellato')], default='pending', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='takeaway.order')),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.piatto')),
            ],
        ),
        migrations.CreateModel(
            name='PiattoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='takeaway.carrello')),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeaway.piatto')),
            ],
        ),
    ]
