# Generated by Django 5.2.6 on 2025-09-08 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0003_carrello_order_orderitem_piattocarrello'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ordine',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='PiattoOrdine',
        ),
    ]
