# Generated by Django 5.2.6 on 2025-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0005_cartafedelta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SogliaSconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punti_richiesti', models.PositiveIntegerField()),
                ('valore_buono', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
