# Generated by Django 5.2.6 on 2025-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0006_sogliasconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sogliasconto',
            name='punti_richiesti',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='sogliasconto',
            name='valore_buono',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
    ]
