# Generated by Django 5.2.6 on 2025-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0007_alter_sogliasconto_punti_richiesti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='sconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
